kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sbocp
  namespace: devcloud1user2-dev
  labels:
    name: sbocp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'sbocp:1.0.0'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: https://github.com/devcloudworkspace/sb-ocp-test.git
      ref: main
    contextDir: /
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
        allowEnv: true
    - type: ConfigChange
  runPolicy: Serial