kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sbocp
  namespace: devcloud1user2-dev
  labels:
    name: sbocp
spec:
  runPolicy: Serial
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
    postCommit: {}
  source:
    type: Git
    git:
      uri: https://github.com/devcloudworkspace/sb-ocp-test.git
      ref: main
    contextDir: /
  output:
    to:
      kind: ImageStreamTag
      name: 'sbocp:1.0.0'
  successfulBuildHistoryLimits: 4
  failureBuildHistoryLimits: 4
  triggers:
    - type: GitHub
      github:
        secret: secret101
        # allowEnv: true
    - type: ImageChange
      imageChange: {}
    - type: Generic
      generic:
        secret: secret101
        allowEnv: true
    - type: ConfigChange