name: Calling Greeter

on:
  push:
    branches: 
      - 'main'

jobs:
  Greeter-Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Greeter
        uses: devcloudworkspace/sb-ocp-test-actions/actions/greeter@main
        with:
          who-to-greet: Everyone
